
BINANCE_API_KEY = '60H2cfydHlhKryRGJbCwWbqbX7lNMAVQjRmier9gy5mx8o0HnlRkRVkKNR7DG9Vr'
BINANCE_SECRET_KEY = 'C2Y9ky5SNnqYzmQIUCPOLnEKuF4XX74jqVvE3VyLfGdRqCEHoCmP27pGShVDG4U4'



SYMBOL = 'USDTARS'
INTERVAL = '1m'
LOOKBACK = 100  # candles for TA

ALERT_THRESHOLDS = {
    "RSI_OVERBOUGHT": 70,
    "RSI_OVERSOLD": 30,
}
